<?php
/**
 * OrderEventType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace robsonek\phpAllegroApi\Model;
use \robsonek\phpAllegroApi\ObjectSerializer;

/**
 * OrderEventType Class Doc Comment
 *
 * @category Class
 * @description Type of order event. * &#x60;BOUGHT&#x60; - purchase without checkout form filled in * &#x60;FILLED_IN&#x60; - checkout form filled in but payment is not completed yet so data could still change * &#x60;READY_FOR_PROCESSING&#x60; - payment completed. Purchase is ready for processing. * &#x60;BUYER_CANCELLED&#x60; - purchase cancelled by buyer * &#x60;FULFILLMENT_STATUS_CHANGED&#x60;: fulfillment status changed. * &#x60;BUYER_MODIFIED&#x60; - purchase modified by buyer * &#x60;AUTO_CANCELLED&#x60; - purchase cancelled automatically by Allegro
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderEventType
{
    /**
     * Possible values of this enum
     */
    public const BOUGHT = 'BOUGHT';

    public const FILLED_IN = 'FILLED_IN';

    public const READY_FOR_PROCESSING = 'READY_FOR_PROCESSING';

    public const BUYER_CANCELLED = 'BUYER_CANCELLED';

    public const FULFILLMENT_STATUS_CHANGED = 'FULFILLMENT_STATUS_CHANGED';

    public const BUYER_MODIFIED = 'BUYER_MODIFIED';

    public const AUTO_CANCELLED = 'AUTO_CANCELLED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BOUGHT,
            self::FILLED_IN,
            self::READY_FOR_PROCESSING,
            self::BUYER_CANCELLED,
            self::FULFILLMENT_STATUS_CHANGED,
            self::BUYER_MODIFIED,
            self::AUTO_CANCELLED
        ];
    }
}


