<?php
/**
 * SaleProductOfferResponseV1AllOfProductSet
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace robsonek\phpAllegroApi\Model;

use \ArrayAccess;
use \robsonek\phpAllegroApi\ObjectSerializer;

/**
 * SaleProductOfferResponseV1AllOfProductSet Class Doc Comment
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SaleProductOfferResponseV1AllOfProductSet implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SaleProductOfferResponseV1_allOf_productSet';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'quantity' => '\robsonek\phpAllegroApi\Model\ProductSetElementQuantityQuantity',
        'safety_information' => '\robsonek\phpAllegroApi\Model\ProductSetElementSafetyInformation',
        'marketed_before_gpsr_obligation' => 'bool',
        'product' => '\robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfProduct',
        'responsible_person' => '\robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfResponsiblePerson',
        'responsible_producer' => '\robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfResponsibleProducer'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'quantity' => null,
        'safety_information' => null,
        'marketed_before_gpsr_obligation' => null,
        'product' => null,
        'responsible_person' => null,
        'responsible_producer' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'quantity' => false,
        'safety_information' => false,
        'marketed_before_gpsr_obligation' => true,
        'product' => false,
        'responsible_person' => false,
        'responsible_producer' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'quantity' => 'quantity',
        'safety_information' => 'safetyInformation',
        'marketed_before_gpsr_obligation' => 'marketedBeforeGPSRObligation',
        'product' => 'product',
        'responsible_person' => 'responsiblePerson',
        'responsible_producer' => 'responsibleProducer'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'quantity' => 'setQuantity',
        'safety_information' => 'setSafetyInformation',
        'marketed_before_gpsr_obligation' => 'setMarketedBeforeGpsrObligation',
        'product' => 'setProduct',
        'responsible_person' => 'setResponsiblePerson',
        'responsible_producer' => 'setResponsibleProducer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'quantity' => 'getQuantity',
        'safety_information' => 'getSafetyInformation',
        'marketed_before_gpsr_obligation' => 'getMarketedBeforeGpsrObligation',
        'product' => 'getProduct',
        'responsible_person' => 'getResponsiblePerson',
        'responsible_producer' => 'getResponsibleProducer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('safety_information', $data ?? [], null);
        $this->setIfExists('marketed_before_gpsr_obligation', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('responsible_person', $data ?? [], null);
        $this->setIfExists('responsible_producer', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets quantity
     *
     * @return \robsonek\phpAllegroApi\Model\ProductSetElementQuantityQuantity|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param \robsonek\phpAllegroApi\Model\ProductSetElementQuantityQuantity|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets safety_information
     *
     * @return \robsonek\phpAllegroApi\Model\ProductSetElementSafetyInformation|null
     */
    public function getSafetyInformation()
    {
        return $this->container['safety_information'];
    }

    /**
     * Sets safety_information
     *
     * @param \robsonek\phpAllegroApi\Model\ProductSetElementSafetyInformation|null $safety_information safety_information
     *
     * @return self
     */
    public function setSafetyInformation($safety_information)
    {
        if (is_null($safety_information)) {
            throw new \InvalidArgumentException('non-nullable safety_information cannot be null');
        }
        $this->container['safety_information'] = $safety_information;

        return $this;
    }

    /**
     * Gets marketed_before_gpsr_obligation
     *
     * @return bool|null
     */
    public function getMarketedBeforeGpsrObligation()
    {
        return $this->container['marketed_before_gpsr_obligation'];
    }

    /**
     * Sets marketed_before_gpsr_obligation
     *
     * @param bool|null $marketed_before_gpsr_obligation Allows you to declare that the product was introduced before 13 Dec 2024 and therefore does not require GPSR data.
     *
     * @return self
     */
    public function setMarketedBeforeGpsrObligation($marketed_before_gpsr_obligation)
    {
        if (is_null($marketed_before_gpsr_obligation)) {
            array_push($this->openAPINullablesSetToNull, 'marketed_before_gpsr_obligation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketed_before_gpsr_obligation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketed_before_gpsr_obligation'] = $marketed_before_gpsr_obligation;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfProduct|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfProduct|null $product product
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets responsible_person
     *
     * @return \robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfResponsiblePerson|null
     */
    public function getResponsiblePerson()
    {
        return $this->container['responsible_person'];
    }

    /**
     * Sets responsible_person
     *
     * @param \robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfResponsiblePerson|null $responsible_person responsible_person
     *
     * @return self
     */
    public function setResponsiblePerson($responsible_person)
    {
        if (is_null($responsible_person)) {
            throw new \InvalidArgumentException('non-nullable responsible_person cannot be null');
        }
        $this->container['responsible_person'] = $responsible_person;

        return $this;
    }

    /**
     * Gets responsible_producer
     *
     * @return \robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfResponsibleProducer|null
     */
    public function getResponsibleProducer()
    {
        return $this->container['responsible_producer'];
    }

    /**
     * Sets responsible_producer
     *
     * @param \robsonek\phpAllegroApi\Model\SaleProductOfferResponseV1AllOfProductSetAllOfResponsibleProducer|null $responsible_producer responsible_producer
     *
     * @return self
     */
    public function setResponsibleProducer($responsible_producer)
    {
        if (is_null($responsible_producer)) {
            throw new \InvalidArgumentException('non-nullable responsible_producer cannot be null');
        }
        $this->container['responsible_producer'] = $responsible_producer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


