<?php
/**
 * OfferTaxSettingsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace robsonek\phpAllegroApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OfferTaxSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description Tax settings for offer. Available settings can be found under &lt;a href&#x3D;\&quot;#operation/getTaxSettingsForCategory\&quot; target&#x3D;\&quot;_blank\&quot;&gt;\&quot;get all tax settings for category\&quot; resource&lt;/a&gt;.
 * @package     robsonek\phpAllegroApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OfferTaxSettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OfferTaxSettings"
     */
    public function testOfferTaxSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exemption"
     */
    public function testPropertyExemption()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
