<?php
/**
 * AdditionalServicesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace robsonek\phpAllegroApi\Test\Api;

use \robsonek\phpAllegroApi\Configuration;
use \robsonek\phpAllegroApi\ApiException;
use \robsonek\phpAllegroApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdditionalServicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdditionalServicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAdditionalServicesGroupUsingPOST
     *
     * Create additional services group.
     *
     */
    public function testCreateAdditionalServicesGroupUsingPOST()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdditionalServicesGroupUsingGET
     *
     * Get the details of an additional services group.
     *
     */
    public function testGetAdditionalServicesGroupUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getListOfAdditionalServicesDefinitionsCategoriesUsingGET
     *
     * Get the additional services definitions by categories.
     *
     */
    public function testGetListOfAdditionalServicesDefinitionsCategoriesUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getListOfAdditionalServicesGroupsUsingGET
     *
     * Get the user's additional services groups.
     *
     */
    public function testGetListOfAdditionalServicesGroupsUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifyAdditionalServicesGroupUsingPUT
     *
     * Modify an additional services group.
     *
     */
    public function testModifyAdditionalServicesGroupUsingPUT()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
