<?php
/**
 * AdvanceShipNoticesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdvanceShipNoticesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdvanceShipNoticesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelAdvanceShipNotice
     *
     * Cancel Advance Ship Notice.
     *
     */
    public function testCancelAdvanceShipNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAdvanceShipNotice
     *
     * Create an Advance Ship Notice.
     *
     */
    public function testCreateAdvanceShipNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAdvanceShipNotice
     *
     * Delete Advance Ship Notice.
     *
     */
    public function testDeleteAdvanceShipNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdvanceShipNotice
     *
     * Get single Advance Ship Notice.
     *
     */
    public function testGetAdvanceShipNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdvanceShipNoticeLabels
     *
     * Get labels for Advance Ship Notice.
     *
     */
    public function testGetAdvanceShipNoticeLabels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdvanceShipNoticeReceivingState
     *
     * Check current state and details of Advance Ship Notice receiving.
     *
     */
    public function testGetAdvanceShipNoticeReceivingState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdvanceShipNotices
     *
     * Get list of Advance Ship Notices.
     *
     */
    public function testGetAdvanceShipNotices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubmitCommand
     *
     * Get submit status.
     *
     */
    public function testGetSubmitCommand()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for submitCommand
     *
     * Submit the Advance Ship Notice.
     *
     */
    public function testSubmitCommand()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAdvanceShipNotice
     *
     * Update Advance Ship Notice.
     *
     */
    public function testUpdateAdvanceShipNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSubmittedAdvanceShipNotice
     *
     * Update submitted Advance Ship Notice.
     *
     */
    public function testUpdateSubmittedAdvanceShipNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
