<?php
/**
 * CategoriesAndParametersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace robsonek\phpAllegroApi\Test\Api;

use \robsonek\phpAllegroApi\Configuration;
use \robsonek\phpAllegroApi\ApiException;
use \robsonek\phpAllegroApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CategoriesAndParametersApiTest Class Doc Comment
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CategoriesAndParametersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for categorySuggestionUsingGET
     *
     * Get categories suggestions.
     *
     */
    public function testCategorySuggestionUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategoriesUsingGET
     *
     * Get IDs of Allegro categories.
     *
     */
    public function testGetCategoriesUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategoryEventsUsingGET1
     *
     * Get changes in categories.
     *
     */
    public function testGetCategoryEventsUsingGET1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategoryParametersScheduledChangesUsingGET1
     *
     * Get planned changes in category parameters.
     *
     */
    public function testGetCategoryParametersScheduledChangesUsingGET1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategoryUsingGET1
     *
     * Get a category by ID.
     *
     */
    public function testGetCategoryUsingGET1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFlatParametersUsingGET2
     *
     * Get parameters supported by a category.
     *
     */
    public function testGetFlatParametersUsingGET2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
