<?php
/**
 * ClassifiedsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClassifiedsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClassifiedsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for assignClassifiedPackagesUsingPUT
     *
     * Assign packages to a classified.
     *
     */
    public function testAssignClassifiedPackagesUsingPUT()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for classifiedOffersStatsGET
     *
     * Get the advertisements daily statistics.
     *
     */
    public function testClassifiedOffersStatsGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for classifiedSellerOfferStatsGET
     *
     * Get the seller's advertisements daily statistics.
     *
     */
    public function testClassifiedSellerOfferStatsGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getClassifiedPackageConfigurationUsingGET
     *
     * Get the configuration of a package.
     *
     */
    public function testGetClassifiedPackageConfigurationUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getClassifiedPackageConfigurationsForCategoryUsingGET
     *
     * Get configurations of packages.
     *
     */
    public function testGetClassifiedPackageConfigurationsForCategoryUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getClassifiedPackagesUsingGET
     *
     * Get classified packages assigned to an offer.
     *
     */
    public function testGetClassifiedPackagesUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
