<?php
/**
 * CompatibilityListApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace robsonek\phpAllegroApi\Test\Api;

use \robsonek\phpAllegroApi\Configuration;
use \robsonek\phpAllegroApi\ApiException;
use \robsonek\phpAllegroApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CompatibilityListApiTest Class Doc Comment
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompatibilityListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCategoriesThatSupportCompatibilityList
     *
     * Get list of categories where compatibility list is supported.
     *
     */
    public function testGetCategoriesThatSupportCompatibilityList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompatibilityListSuggestion
     *
     * Get suggested compatibility list..
     *
     */
    public function testGetCompatibilityListSuggestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompatibleProducts
     *
     * Get list of compatible products.
     *
     */
    public function testGetCompatibleProducts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompatibleProductsGroups
     *
     * Get list of compatible product groups.
     *
     */
    public function testGetCompatibleProductsGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
