<?php
/**
 * ParcelManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace robsonek\phpAllegroApi\Test\Api;

use \robsonek\phpAllegroApi\Configuration;
use \robsonek\phpAllegroApi\ApiException;
use \robsonek\phpAllegroApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ParcelManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  robsonek\phpAllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ParcelManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelParcel
     *
     * Cancel parcel.
     *
     */
    public function testCancelParcel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNewParcel
     *
     * Create a new parcel.
     *
     */
    public function testCreateNewParcel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAvailableDeliveryServices
     *
     * Get available delivery services.
     *
     */
    public function testGetAvailableDeliveryServices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelCancellationStatus
     *
     * Get parcel cancellation status.
     *
     */
    public function testGetParcelCancellationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelCreationStatus
     *
     * Get parcel creation status.
     *
     */
    public function testGetParcelCreationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelDetails
     *
     * Get parcel details.
     *
     */
    public function testGetParcelDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelLabel
     *
     * Get parcel label.
     *
     */
    public function testGetParcelLabel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelPickupStatus
     *
     * Get parcel pickup status.
     *
     */
    public function testGetParcelPickupStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelsPickupDateProposals
     *
     * Get parcels pickup date proposals.
     *
     */
    public function testGetParcelsPickupDateProposals()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getParcelsProtocol
     *
     * Get parcels protocol.
     *
     */
    public function testGetParcelsProtocol()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestParcelPickup
     *
     * Request parcel pickup.
     *
     */
    public function testRequestParcelPickup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
